version: "3.5"
services:
    nebula:
        privileged: true
        cap_add:
           - "NET_ADMIN"
        devices:
           - /dev/net/tun:/dev/net/tun
        image: nebula:latest
        restart: on-failure
        ports:
            - target: 4242
              published: 4242
              protocol: udp
        command: ["-config", "/opt/nebula/config.yaml"]
        volumes:
            - "./config.lighthouse.yaml:/opt/nebula/config.yaml"
            - "./ca.crt:/opt/nebula/ca.crt"
            - "./lighthouse1.crt:/opt/nebula/lighthouse1.crt"
            - "./lighthouse1.key:/opt/nebula/lighthouse1.key"
